### ISSUE TITLE
Project intro missing

### ISSUE THREAD

**Issue by sskras** [Alexey1994/Rabbit#1]
Hello and thanks for the interesting code.

I guess an intro (even a minimal one) would help people to get familiar with the project.

Eg. to me it's not clear what's the purpose, except for that it's an OS (including the 16-bit bootloader).

**Comment by Alexey1994** [comment]
Done, readme.md added

**Comment by sskras** [comment]
Thanks a lot! 

Also, is your new 32-bit, BIOS-services based OS available/open source?

**Comment by Alexey1994** [comment]
Yes, it will be published under the MIT license

**Comment by Alexey1994** [comment]
> Thanks a lot!
> 
> Also, is your new 32-bit, BIOS-services based OS available/open source?

I publish my new OS project here https://github.com/Alexey1994/BelOS
